import{a as g,S as d,i}from"./assets/vendor-BkC4bTqC.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerPolicy&&(t.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?t.credentials="include":r.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(r){if(r.ep)return;r.ep=!0;const t=n(r);fetch(r.href,t)}})();const y="55187145-d3b914f8bfc13386f944f455c",m="https://pixabay.com/api/";async function p(e,o=1,n=12){try{return(await g.get(m,{params:{key:y,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:n}})).data}catch(s){throw console.error("Error fetching images:",s),s}}function h(e,o=1,n=12){return p(e,o,n)}let l;function L(e){const o=document.querySelector(".gallery");o.innerHTML=e.map(({webformatURL:n,largeImageURL:s,tags:r,likes:t,views:a,comments:u,downloads:f})=>`<li class="gallery-item">
          <a href="${s}">
            <img src="${n}" alt="${r}" loading="lazy" />
          </a>
          <div class="info">
            <p><strong>Likes:</strong> ${t}</p>
            <p><strong>Views:</strong> ${a}</p>
            <p><strong>Comments:</strong> ${u}</p>
            <p><strong>Downloads:</strong> ${f}</p>
          </div>
        </li>`).join(""),l?l.refresh():l=new d(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250})}function q(){const e=document.querySelector(".gallery");e.innerHTML=""}function S(){const e=document.querySelector(".loader");e&&(e.style.display="block")}function c(){const e=document.querySelector(".loader");e&&(e.style.display="none")}const b=document.querySelector(".form");document.querySelector(".gallery");b.addEventListener("submit",e=>{e.preventDefault();const o=e.target.elements["search-text"].value.trim();if(!o){i.warning({title:"Warning",message:"Please enter a search query!"});return}S(),q(),h(o).then(n=>{if(c(),!n.hits.length){i.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"});return}L(n.hits)}).catch(n=>{c(),i.error({title:"Error",message:"Failed to fetch images. Try again later."}),console.error(n)})});
//# sourceMappingURL=index.js.map
